# Generated by Django 2.2 on 2019-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hopital_id', models.CharField(max_length=20)),
                ('hospital_name', models.CharField(max_length=150)),
                ('hospital_mail', models.EmailField(max_length=254)),
                ('Hopital_t_beds', models.IntegerField(default='0')),
                ('Hopital_r_beds', models.IntegerField(default='0')),
                ('Hopital_v_beds', models.IntegerField(default='0')),
                ('Hospital_pass', models.CharField(max_length=30)),
            ],
        ),
    ]
