# Generated by Django 2.2 on 2019-08-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_hospital', models.CharField(max_length=20)),
                ('P_name', models.CharField(max_length=20)),
                ('A_name', models.CharField(max_length=150)),
                ('Mobile', models.IntegerField(max_length=15)),
                ('P_address', models.CharField(max_length=30)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
